import { ProjectData } from "./types";

export const REAL_PROJECTS_DATA: any[] = [
  {
    no: 1,
    namaProject: "[Z1-GOV] IPPJU Ampera Raya",
    pmoId: "PMO-GOV-001",
    projectId: "",
    jabo: "Jabo 1",
    projectPlan: "Q1-26",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.NATAMA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "30-Oct-23",
    tahun: "2023",
    bulan: "November",
    lengthM: 10000,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Belum Survey",
    statusSurveyLabour: "Belum Survey",
    requestType: "Cancel",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Not Started",
    categoryConstruction: "Permit",
    progressConstruction: 0,
    dateUpdate: ""
  },
  {
    no: 2,
    namaProject: "[Z1-GOV] IPPJU Cideng",
    pmoId: "PMO-GOV-002",
    projectId: "",
    jabo: "Jabo 1",
    projectPlan: "Q1-26",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.RPA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "12-Jun-24",
    tahun: "2023",
    bulan: "November",
    lengthM: 8500,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "Prepare Dokumen",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 90,
    dateUpdate: ""
  },
  {
    no: 3,
    namaProject: "[Z1-GOV] IPPJU DI Panjaitan",
    pmoId: "PMO-GOV-003",
    projectId: "",
    jabo: "Jabo 1",
    projectPlan: "Q1-26",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.ARKON",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "3-Sep-24",
    tahun: "2023",
    bulan: "November",
    lengthM: 2600,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Belum Survey",
    statusSurveyLabour: "Belum Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Not Started",
    categoryConstruction: "Permit",
    progressConstruction: 0,
    dateUpdate: ""
  },
  {
    no: 4,
    namaProject: "[Z1-GOV] Pengamanan JL. Karet tangerang",
    pmoId: "PMO-GOV-004",
    projectId: "No Need SAP",
    jabo: "Jabo 1",
    projectPlan: "",
    areaKota: "West",
    pic: "Ardyansyah",
    waspang: "",
    vendor: "Internal Team",
    metodeProject: "Pengamanan Asset",
    tanggalSurat: "3-Sep-24",
    tahun: "2024",
    bulan: "Januari",
    lengthM: 500,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "No Need",
    statusSurveyLabour: "No Need",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "No Need",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Done Pengamanan",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 5,
    namaProject: "[Z1-GOV] Jl Daan Mogot sisi Selatan",
    pmoId: "PMO-GOV-005",
    projectId: "No Need SAP",
    jabo: "Jabo 1",
    projectPlan: "",
    areaKota: "West",
    pic: "Mega",
    waspang: "",
    vendor: "Belum Ada Vendor",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "3-Sep-24",
    tahun: "2024",
    bulan: "Januari",
    lengthM: 1200,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "No Need",
    statusSurveyLabour: "No Need",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Pending",
    categoryConstruction: "Pending",
    progressConstruction: 0,
    dateUpdate: ""
  },
  {
    no: 6,
    namaProject: "[Z1-GOV] Tebet barat Lanjutan",
    pmoId: "PMO-GOV-006",
    projectId: "GOV0000451",
    jabo: "Jabo 1",
    projectPlan: "",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.RPA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "3-Sep-24",
    tahun: "2023",
    bulan: "Oktober",
    lengthM: 1610,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Cancel",
    statusSurveyLabour: "Cancel",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "Cancel Project",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Cancelled",
    categoryConstruction: "Cancelled",
    progressConstruction: 0,
    dateUpdate: ""
  },
  {
    no: 7,
    namaProject: "[Z1-GOV] Jl. Joglo Raya Permanent",
    pmoId: "PMO-GOV-007",
    projectId: "GOV0000486",
    jabo: "Jabo 1",
    projectPlan: "Q2",
    areaKota: "West",
    pic: "Ardyansyah",
    waspang: "",
    vendor: "PT.MAS",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "3-Sep-24",
    tahun: "2024",
    bulan: "Januari",
    lengthM: 1070,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "Released",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 8,
    namaProject: "[Z1-GOV] Bad cable Srengseng raya",
    pmoId: "PMO-GOV-008",
    projectId: "IM00000885",
    jabo: "Jabo 1",
    projectPlan: "Q1",
    areaKota: "West",
    pic: "Ardyansyah",
    waspang: "",
    vendor: "PT.FITEL",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "3-Sep-24",
    tahun: "2024",
    bulan: "Februari",
    lengthM: 650,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "Released",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 11,
    namaProject: "Relokasi Additional Jl.Kayu putih raya",
    pmoId: "PMO-GOV-011",
    projectId: "GOV0000416GOV0000453",
    jabo: "Jabo 3",
    projectPlan: "Q2",
    areaKota: "NE",
    pic: "Daud",
    waspang: "",
    vendor: "PT.ARKON",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "3-Sep-24",
    tahun: "2024",
    bulan: "Februari",
    lengthM: 750,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "No Need",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "Old Data",
    typePoLabour: "Released",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 12,
    namaProject: "Relokasi Jl Candrawasih",
    pmoId: "PMO-GOV-012",
    projectId: "GOV0000491,GOV0000544",
    jabo: "Jabo 2",
    projectPlan: "Q2",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.TRP",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "3-Sep-24",
    tahun: "2024",
    bulan: "Februari",
    lengthM: 2200,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "Old Data",
    typePoLabour: "Released",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 13,
    namaProject: "[Z1-GOV] JPO Mas Mansyur",
    pmoId: "PMO-GOV-013",
    projectId: "GOV0000535",
    jabo: "Jabo 1",
    projectPlan: "Q4-26",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.TRIMASS",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "3-Sep-24",
    tahun: "2022",
    bulan: "November",
    lengthM: 200,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Pending",
    categoryConstruction: "Pending",
    progressConstruction: 0,
    dateUpdate: ""
  },
  {
    no: 14,
    namaProject: "Relokasi Jl Menjangan Raya - Kompas",
    pmoId: "PMO-GOV-014",
    projectId: "GOV0000521",
    jabo: "Jabo 2",
    projectPlan: "Q2",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.REKATAMA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "24-Sep-24",
    tahun: "2024",
    bulan: "Februari",
    lengthM: 3200,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "32045109",
    typePoLabour: "Released",
    statusPengajuanPo: "GOV0000521",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 24,
    namaProject: "[Z1-GOV] LRT Tambak-Minangkabau-Manggarai",
    pmoId: "PMO-GOV-024",
    projectId: "GOV0000584,GOV0000715",
    jabo: "Jabo 1",
    projectPlan: "Q3",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.RPA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "30-Oct-24",
    tahun: "2025",
    bulan: "Mei",
    lengthM: 5100,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-TREBOR-APJ",
    volume: "3705",
    poNumber: "32049192",
    typePoLabour: "Released",
    statusPengajuanPo: "GOV0000715",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 30,
    namaProject: "Relokasi Jl, Pegangsaan dua - Logistic",
    pmoId: "PMO-GOV-030",
    projectId: "GOV0000540",
    jabo: "Jabo 3",
    projectPlan: "Q3",
    areaKota: "NE",
    pic: "Daud",
    waspang: "",
    vendor: "PT.LISMA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "6-Dec-24",
    tahun: "2024",
    bulan: "Juni",
    lengthM: 3992,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-TREKAT-APJ",
    volume: "3992",
    poNumber: "",
    typePoLabour: "Submitted to PBO",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 37,
    namaProject: "[Z1-GOV] SDA Jl. Kramat Asem Kecil",
    pmoId: "PMO-GOV-018",
    projectId: "No Need SAP",
    jabo: "Jabo 1",
    projectPlan: "",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "Internal Team",
    metodeProject: "Pengamanan Asset",
    tanggalSurat: "4/23/2025",
    tahun: "2024",
    bulan: "Februari",
    lengthM: 500,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "",
    typePoLabour: "",
    StatusPengajuanPo: "No Need",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Done Pengamanan",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 51,
    namaProject: "Relokasi Dewi Sartika Depok",
    pmoId: "PMO-GOV-051",
    projectId: "GOV0000680",
    jabo: "Jabo 2",
    projectPlan: "Q3-26",
    areaKota: "South",
    pic: "Chaerulloh/Fikri",
    waspang: "",
    vendor: "PT.FITEL",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "23-Jun-25",
    tahun: "2024",
    bulan: "Juni",
    lengthM: 1130,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-TREKAT-APJ",
    volume: "1998",
    poNumber: "32049865",
    typePoLabour: "Released",
    statusPengajuanPo: "GOV0000680",
    remarks: "",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 80,
    dateUpdate: ""
  },
  {
    no: 180,
    namaProject: "Relokasi Jl. Jatimekar-Jatikeramat",
    pmoId: "PMO-GOV-180",
    projectId: "GOV0000655/GOV0000743",
    jabo: "Jabo 3",
    projectPlan: "Q4",
    areaKota: "Beka",
    pic: "Daud",
    waspang: "",
    vendor: "PT.FITEL",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "30-Oct-24",
    tahun: "2024",
    bulan: "Oktober",
    lengthM: 6600,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-TREKAT-APJ",
    volume: "6600",
    poNumber: "32049398",
    typePoLabour: "Released",
    statusPengajuanPo: "GOV0000743",
    remarks: "",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 60,
    dateUpdate: ""
  },
  {
    no: 214,
    namaProject: "[Z1-GOV] Jl. Pluit Permai Raya",
    pmoId: "PMO-GOV-214",
    projectId: "GOV0000596",
    jabo: "Jabo 1",
    projectPlan: "Q3",
    areaKota: "West",
    pic: "Mega",
    waspang: "",
    vendor: "PT.SENTRATEL",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "13-Sep-24",
    tahun: "2024",
    bulan: "November",
    lengthM: 3000,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "",
    volume: "7954",
    poNumber: "32047464",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000596",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 219,
    namaProject: "Relokasi Jl Pondok Cabe",
    pmoId: "PMO-GOV-219",
    projectId: "GOV0000658",
    jabo: "Jabo 2",
    projectPlan: "Q3",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.REKATAMA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "15-Jan-24",
    tahun: "2026",
    bulan: "Mei",
    lengthM: 4500,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-TREBOR-PU",
    volume: "6503",
    poNumber: "32049717",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000658",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 85,
    dateUpdate: ""
  },
  {
    no: 224,
    namaProject: "Relokasi Jl Pondok Jaya",
    pmoId: "PMO-GOV-224",
    projectId: "GOV0000532,GOV0000738",
    jabo: "Jabo 2",
    projectPlan: "Q3",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT CMT",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2024-01-01",
    tahun: "2026",
    bulan: "Mei",
    lengthM: 2900,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-TREKAT-APJ",
    volume: "2321",
    poNumber: "32049299",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000738",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 80,
    dateUpdate: ""
  },
  {
    no: 226,
    namaProject: "Relokasi JL.Pejuang (Kaliabang)",
    pmoId: "PMO-GOV-226",
    projectId: "GOV0000625,GOV0000734",
    jabo: "Jabo 3",
    projectPlan: "Q4",
    areaKota: "NE",
    pic: "Daud",
    waspang: "",
    vendor: "PT.SBKP",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "16-Dec-24",
    tahun: "2024",
    bulan: "Desember",
    lengthM: 4313,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-TREKAT-APJ",
    volume: "4313",
    poNumber: "32049287",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000734",
    statusConstruction: "In Progress",
    categoryConstruction: "Pulling Cable",
    progressConstruction: 90,
    dateUpdate: ""
  },
  {
    no: 241,
    namaProject: "Relokasi JL MH Tamrin Lnjt",
    pmoId: "PMO-GOV-241",
    projectId: "GOV0000593,GOV0000733",
    jabo: "Jabo 2",
    projectPlan: "Q4",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.SDM",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2024-01-01",
    tahun: "2026",
    bulan: "Mei",
    lengthM: 2800,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-TREBOR-PU",
    volume: "3790",
    poNumber: "32049286",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000733",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 256,
    namaProject: "Relokasi Jl.Danau Sunter sisi Barat B",
    pmoId: "PMO-GOV-256",
    projectId: "GOV0000563,GOV0000643GOV0000681",
    jabo: "Jabo 3",
    projectPlan: "Q3",
    areaKota: "NE",
    pic: "Daud",
    waspang: "",
    vendor: "PT.ANT",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "28/2/0205",
    tahun: "2025",
    bulan: "Februari",
    lengthM: 5448,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "-",
    poNumber: "32048509",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000681",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 257,
    namaProject: "Relokasi Rumah Cak Imin kemang Dalam",
    pmoId: "PMO-GOV-257",
    projectId: "GOV0000568,GOV0000768",
    jabo: "Jabo 1",
    projectPlan: "Q3",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.INFRA LINTAS NUSANTARA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "11/2/2025",
    tahun: "2025",
    bulan: "Februari",
    lengthM: 1964,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour Fo",
    labour: "PGOV-XXMOB",
    volume: "1",
    poNumber: "",
    typePoLabour: "Sourcing Coupa",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 260,
    namaProject: "Relokasi Jl.Jendral Sudirman Bogor",
    pmoId: "PMO-GOV-260",
    projectId: "GOV0000668",
    jabo: "Jabo 2",
    projectPlan: "Q1",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.SENTRATEL",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-03-04",
    tahun: "2025",
    bulan: "Februari",
    lengthM: 2361,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-HFCSURVEY",
    volume: "1",
    poNumber: "32049513",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000668",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 273,
    namaProject: "RELOKASI Jl. Pelita (Antasari To Kemang)",
    pmoId: "PMO-GOV-273",
    projectId: "GOV0000600,GOV0000769",
    jabo: "Jabo 1",
    projectPlan: "Q4",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.INFRA LINTAS NUSANTARA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "4/15/2025",
    tahun: "2025",
    bulan: "April",
    lengthM: 1500,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-XXMOB",
    volume: "1",
    poNumber: "32049634",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000769",
    statusConstruction: "In Progress",
    categoryConstruction: "Pulling Cable",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 383,
    namaProject: "Relokasi Jl. Pilar Raya dan Jl. Kedoya Pesing Jakarta Barat",
    pmoId: "PMO-GOV-383",
    projectId: "",
    jabo: "Jabo 1",
    projectPlan: "Q4",
    areaKota: "West",
    pic: "Mega",
    waspang: "",
    vendor: "PT.PRAGATA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "4/22/2025",
    tahun: "2025",
    bulan: "April",
    lengthM: 1040,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-TREKAT-APJ",
    volume: "1215",
    poNumber: "",
    typePoLabour: "Prepare Dokumen",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 386,
    namaProject: "Relokasi Jl. Brigjen Katamso Kota Bambu Jakarta Barat",
    pmoId: "PMO-GOV-386",
    projectId: "GOV0000651,GOV0000777",
    jabo: "Jabo 1",
    projectPlan: "Q4",
    areaKota: "West",
    pic: "Mega",
    waspang: "",
    vendor: "PT.RPA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "4/22/2025",
    tahun: "2025",
    bulan: "April",
    lengthM: 2261,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-TREKAT-APJ",
    volume: "2638",
    poNumber: "32049850",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000777",
    statusConstruction: "In Progress",
    categoryConstruction: "Pulling Cable",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 401,
    namaProject: "Relokasi Jl.Serua Depok",
    pmoId: "PMO-GOV-401",
    projectId: "GOV0000609,GOV0000736",
    jabo: "Jabo 2",
    projectPlan: "Q4",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.SBKP",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "28/4/2025",
    tahun: "2025",
    bulan: "Mei",
    lengthM: 2174,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-TREKAT-APJ",
    volume: "",
    poNumber: "32049289",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000736",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 402,
    namaProject: "Relokasi Jl.Tapos Depok",
    pmoId: "PMO-GOV-402",
    projectId: "",
    jabo: "Jabo 2",
    projectPlan: "Q1",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.CPS",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-04-28",
    tahun: "2025",
    bulan: "Mei",
    lengthM: 3000,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-HFCSURVEY",
    volume: "1",
    poNumber: "",
    typePoLabour: "Approval PMO",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "Project Done",
    categoryConstruction: "Ready To CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 418,
    namaProject: "Relokasi Jalan Kertamukti Tangerang",
    pmoId: "PMO-GOV-418",
    projectId: "GOV0000650",
    jabo: "Jabo 2",
    projectPlan: "Q4",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.REKATAMA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "1-Mar-25",
    tahun: "2025",
    bulan: "Mei",
    lengthM: 2000,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "",
    volume: "",
    poNumber: "32048149",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000650",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 85,
    dateUpdate: ""
  },
  {
    no: 422,
    namaProject: "Relokasi Jalan Pondok Betung Tangerang",
    pmoId: "PMO-GOV-422",
    projectId: "GOV0000659",
    jabo: "Jabo 2",
    projectPlan: "Q4",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.REKATAMA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-03-01",
    tahun: "2025",
    bulan: "Mei",
    lengthM: 2284,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-TREBOR-PU",
    volume: "2284",
    poNumber: "",
    typePoLabour: "Submitted to PBO",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 85,
    dateUpdate: ""
  },
  {
    no: 430,
    namaProject: "Relokasi Jalan Raden Fatah, Tangerang",
    pmoId: "PMO-GOV-430",
    projectId: "GOV0000656",
    jabo: "Jabo 2",
    projectPlan: "Q4",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.DAVON",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-06-01",
    tahun: "2025",
    bulan: "Juni",
    lengthM: 3715,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-BORKAT-PU",
    volume: "3715",
    poNumber: "",
    typePoLabour: "Sourcing Coupa",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "In Progress",
    categoryConstruction: "Pulling Cable",
    progressConstruction: 85,
    dateUpdate: ""
  },
  {
    no: 431,
    namaProject: "Relokasi Jalan Hasyim Ashari Tangerang",
    pmoId: "PMO-GOV-431",
    projectId: "",
    jabo: "Jabo 2",
    projectPlan: "Q4-26",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.DAVON",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "26-Jun-25",
    tahun: "2025",
    bulan: "Mei",
    lengthM: 3600,
    apdRelokasi: "Ada",
    statusAudit: "Ada",
    apdLinknet: "Ada",
    baSurvey: "Ada",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-PRTGLV-APJ",
    volume: "18",
    poNumber: "",
    typePoLabour: "Approval P&D",
    statusPengajuanPo: "",
    remarks: "",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 20,
    dateUpdate: ""
  },
  {
    no: 471,
    namaProject: "Relokasi Jl.Gunung Sahari Jakarta Pusat",
    pmoId: "PMO-GOV-471",
    projectId: "GOV0000648,GOV0000755",
    jabo: "Jabo 1",
    projectPlan: "Q4",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.OLT",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "15-Jul-25",
    tahun: "2025",
    bulan: "Mei",
    lengthM: 800,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "",
    labour: "PGOV-TREKAT-APJ",
    volume: "",
    poNumber: "32049467",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000755",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 480,
    namaProject: "Relokasi Mayor Oking",
    pmoId: "PMO-GOV-480",
    projectId: "GOV0000588,GOV0000698",
    jabo: "Jabo 2",
    projectPlan: "Q4",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.JWS",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "17-Jun-25",
    tahun: "2025",
    bulan: "Mei",
    lengthM: 3813,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-TREKAT-APJ",
    volume: "3813",
    poNumber: "32049514",
    TypePOLabour: "Released",
    StatusPengajuanPO: "GOV0000698",
    Remarks: "A2601159, A2601003",
    StatusConstruction: "Project Done",
    CategoryConstruction: "Ready To CO",
    ProgressConstruction: 100,
    DateUpdate: ""
  },
  {
    No: 489,
    NamaProject: "Relokasi Jl. Bandengan (PT.Pragata)",
    PMO_ID: "PMO-GOV-489",
    ProjectID: "",
    Jabo: "Jabo 1",
    ProjectPlan: "Q1-26",
    AreaKota: "West",
    PIC: "Mega",
    Waspang: "",
    Vendor: "PT.PRAGATA",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "",
    Tahun: 2025,
    Bulan: "Juni",
    LengthM: 21300,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Civil Work",
    ProgressConstruction: 60,
    DateUpdate: ""
  },
  {
    No: 490,
    NamaProject: "Relokasi Kembangan Utara",
    PMO_ID: "PMO-GOV-490",
    ProjectID: "GOV0000623.GOV0000762",
    Jabo: "Jabo 1",
    ProjectPlan: "Q4",
    AreaKota: "West",
    PIC: "Mega",
    Waspang: "",
    Vendor: "PT.CAPER",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "",
    Tahun: 2025,
    Bulan: "Juli",
    LengthM: 3680,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Pulling Cable",
    ProgressConstruction: 75,
    DateUpdate: ""
  },
  {
    No: 491,
    NamaProject: "Relokasi Pluit Putri",
    PMO_ID: "PMO-GOV-491",
    ProjectID: "GOV0000595",
    Jabo: "Jabo 1",
    ProjectPlan: "Q4",
    AreaKota: "West",
    PIC: "Mega",
    Waspang: "",
    Vendor: "PT.PHPE",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "",
    Tahun: 2025,
    Bulan: "Juni",
    LengthM: 4038,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Ready To CO",
    ProgressConstruction: 100,
    DateUpdate: ""
  },
  {
    No: 492,
    NamaProject: "Relokasi Sumenep",
    PMO_ID: "PMO-GOV-492",
    ProjectID: "GOV0000691",
    Jabo: "Jabo 1",
    ProjectPlan: "Q1-26",
    AreaKota: "Central",
    PIC: "Mega",
    Waspang: "",
    Vendor: "PT.FBI",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "14-Aug-2025",
    Tahun: 2025,
    Bulan: "Juli",
    LengthM: 2300,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Pulling Cable",
    ProgressConstruction: 100,
    DateUpdate: ""
  },
  {
    No: 493,
    NamaProject: "Relokasi Hos Cokroaminoto tahap 2 Menteng",
    PMO_ID: "PMO-GOV-493",
    ProjectID: "GOV0000640,GOV0000703",
    Jabo: "Jabo 1",
    ProjectPlan: "Q4",
    AreaKota: "Central",
    PIC: "Mega",
    Waspang: "",
    Vendor: "PT.SENTRATEL",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "14-Aug-2025",
    Tahun: 2025,
    Bulan: "Juli",
    LengthM: 2000,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Pulling Cable",
    ProgressConstruction: 100,
    DateUpdate: ""
  },
  {
    No: 497,
    NamaProject: "Relokasi Jl.RS Fatmawati Jak Sel",
    PMO_ID: "PMO-GOV-497",
    ProjectID: "GOV0000666",
    Jabo: "Jabo 2",
    ProjectPlan: "Q1",
    AreaKota: "South",
    PIC: "Chaerulloh",
    Waspang: "",
    Vendor: "PT.FIROPTIK",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "22-Aug-2025",
    Tahun: 2025,
    Bulan: "Juli",
    LengthM: 1891,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Ready To CO",
    ProgressConstruction: 100,
    DateUpdate: ""
  },
  {
    No: 501,
    NamaProject: "Relokasi Jl.Kweni 2 Jakarta Pusat",
    PMO_ID: "PMO-GOV-501",
    ProjectID: "GOV0000649,GOV0000754",
    Jabo: "Jabo 1",
    ProjectPlan: "Q4",
    AreaKota: "Central",
    PIC: "Mega",
    Waspang: "",
    Vendor: "PT.OLT",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "11/8/2025",
    Tahun: 2025,
    Bulan: "Juli",
    LengthM: 900,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Pulling Cable",
    ProgressConstruction: 100,
    DateUpdate: ""
  },
  {
    No: 511,
    NamaProject: "Relokasi Jl.Veteran Serang, Jl.Sam'un, Jl.Mayor Syafei",
    PMO_ID: "PMO-GOV-511",
    ProjectID: "GOV0000760",
    Jabo: "Jabo 2",
    ProjectPlan: "Q4",
    AreaKota: "Tangerang",
    PIC: "ARIS BARON",
    Waspang: "",
    Vendor: "PT.TRP",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "15-Dec-25",
    Tahun: 2026,
    Bulan: "Februari",
    LengthM: 4809,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Civil Work",
    ProgressConstruction: 60,
    DateUpdate: ""
  },
  {
    No: 514,
    NamaProject: "Relokasi Cilegon Segmen 2",
    PMO_ID: "PMO-GOV-514",
    ProjectID: "GOV0000635,GOV0000765,GOV0000714",
    Jabo: "Jabo 2",
    ProjectPlan: "Q4",
    AreaKota: "Tangerang",
    PIC: "ARIS BARON",
    Waspang: "",
    Vendor: "PT.TRP",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "2025-09-01",
    Tahun: 2025,
    Bulan: "September",
    LengthM: 3600,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "Project Done",
    CategoryConstruction: "Done CO",
    ProgressConstruction: 100,
    DateUpdate: ""
  },
  {
    No: 529,
    NamaProject: "Pelebaran jalan nasional pada jln jajaran banjir kanal timur Rorotan 2,3,4",
    PMO_ID: "PMO-GOV-529",
    ProjectID: "GOV0000750",
    Jabo: "Jabo 3",
    ProjectPlan: "Q4",
    AreaKota: "NE",
    PIC: "Daud",
    Waspang: "",
    Vendor: "PT.FBI",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "4/21/2025",
    Tahun: 2025,
    Bulan: "Juli",
    LengthM: 106,
    StatusSurveyMaterial: "No Need",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "Project Done",
    CategoryConstruction: "Done CO",
    ProgressConstruction: 100,
    DateUpdate: ""
  },
  {
    No: 572,
    NamaProject: "Relokasi JL Puspitek Segmen 2",
    PMO_ID: "PMO-GOV-572",
    ProjectID: "",
    Jabo: "Jabo 2",
    ProjectPlan: "Q4-26",
    AreaKota: "Tangerang",
    PIC: "ARIS BARON",
    Waspang: "",
    Vendor: "PT.REKATAMA",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "08/01/2025",
    Tahun: 2025,
    Bulan: "Agustus",
    LengthM: 14500,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Civil Work",
    ProgressConstruction: 50,
    DateUpdate: ""
  },
  {
    No: 573,
    NamaProject: "Relokasi Jl.Penggilingan raya",
    PMO_ID: "PMO-GOV-573",
    ProjectID: "GOV0000641,GOV0000782",
    Jabo: "Jabo 3",
    ProjectPlan: "Q4",
    AreaKota: "NE",
    PIC: "Daud",
    Waspang: "",
    Vendor: "PT.SENTRATEL",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "23/06/2025",
    Tahun: 2025,
    Bulan: "Agustus",
    LengthM: 4435,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Civil Work",
    ProgressConstruction: 40,
    DateUpdate: ""
  },
  {
    No: 581,
    NamaProject: "Relokasi JL Syeh Nawawi Pemda",
    PMO_ID: "PMO-GOV-581",
    ProjectID: "GOV0000752",
    Jabo: "Jabo 2",
    ProjectPlan: "Q4-26",
    AreaKota: "Tangerang",
    PIC: "ARIS BARON",
    Waspang: "",
    Vendor: "PT.MANDAU",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "23-Oct-25",
    Tahun: 2026,
    Bulan: "April",
    LengthM: 6780,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Civil Work",
    ProgressConstruction: 60,
    DateUpdate: ""
  },
  {
    No: 595,
    NamaProject: "Relokasi Mandor Iren - Sunter Permai",
    PMO_ID: "PMO-GOV-595",
    ProjectID: "GOV0000637,GOV0000642",
    Jabo: "Jabo 3",
    ProjectPlan: "Q4",
    AreaKota: "NE",
    PIC: "Daud",
    Waspang: "",
    Vendor: "PT.SENTRATEL",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "16-Jul-25",
    Tahun: 2025,
    Bulan: "Agustus",
    LengthM: 2859,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "In Progress",
    CategoryConstruction: "Ready To CO",
    ProgressConstruction: 95,
    DateUpdate: ""
  },
  {
    No: 597,
    NamaProject: "Relokasi Jl Pahlawan Ciputat",
    PMO_ID: "PMO-GOV-597",
    ProjectID: "GOV0000664",
    Jabo: "Jabo 2",
    ProjectPlan: "Q4-26",
    AreaKota: "Tangerang",
    PIC: "ARIS BARON",
    Waspang: "",
    Vendor: "PT.TRP",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "1-Aug-25",
    Tahun: 2025,
    Bulan: "Agustus",
    LengthM: 8069,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    StatusConstruction: "Project Done",
    CategoryConstruction: "Done CO",
    ProgressConstruction: 100,
    DateUpdate: ""
  },
  {
    No: 613,
    NamaProject: "Relokasi JL Pramuka Depok",
    PMO_ID: "PMO-GOV-613",
    ProjectID: "GOV0000688",
    Jabo: "Jabo 2",
    ProjectPlan: "Q1",
    AreaKota: "South",
    PIC: "Chaerulloh",
    Waspang: "",
    Vendor: "PT.MANDAU",
    MetodeProject: "Relokasi By Apjatel",
    TanggalSurat: "2025-04-28",
    Tahun: 2025,
    Bulan: "Oktober",
    LengthM: 3381,
    StatusSurveyMaterial: "Sudah Survey",
    StatusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-HFCSURVEY",
    volume: "1",
    poNumber: "32049405",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000688",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 615,
    namaProject: "Relokasi Jl Raya Bekasi - Ujung Menteng",
    pmoId: "PMO-GOV-615",
    projectId: "GOV0000702",
    jabo: "Jabo 3",
    projectPlan: "Q3-26",
    areaKota: "NE",
    pic: "Daud",
    waspang: "",
    vendor: "PT.FBI",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "29/07/2025",
    tahun: "2025",
    bulan: "Juli",
    lengthM: 1112,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour",
    labour: "PGOV-XXMOB",
    volume: "1",
    poNumber: "",
    typePoLabour: "Submitted to PBO",
    statusPengajuanPo: "",
    remarks: "A2600935",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 95,
    dateUpdate: ""
  },
  {
    No: 616,
    NamaProject: "Relokasi Perumahan Reswara Park, Jl.Mini 3 Cipayung-Taman Mini",
    PMO_ID: "PMO-GOV-616",
    ProjectID: "GOV0000745",
    jabo: "Jabo 3",
    projectPlan: "Q1-26",
    areaKota: "Beka",
    pic: "Daud",
    waspang: "",
    vendor: "PT.PHPE",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2026-01-02",
    tahun: "2025",
    bulan: "Oktober",
    lengthM: 975,
    apdRelokasi: "",
    statusAudit: "",
    apdLinknet: "",
    baSurvey: "",
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    requestType: "Labour Coax",
    labour: "PGOV-TREKAT-APJ",
    volume: "887",
    poNumber: "32049400",
    typePoLabour: "",
    statusPengajuanPo: "Released",
    remarks: "GOV0000745",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 621,
    namaProject: "Relokasi PDAM Jl. Raya Bogor, Kab.Bogor",
    pmoId: "PMO-GOV-621",
    projectId: "GOV0000667",
    jabo: "Jabo 2",
    projectPlan: "Q1-26",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.MANDAU",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-10-10",
    tahun: "2025",
    bulan: "November",
    lengthM: 295,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "Project Done",
    categoryConstruction: "Done Co",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 622,
    namaProject: "Relokasi Jl. Mayor Oking ( lanjutan ), Kab. Bogor",
    pmoId: "PMO-GOV-622",
    projectId: "GOV0000676",
    jabo: "Jabo 2",
    projectPlan: "Q1-26",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.PICA",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-11-24",
    tahun: "2025",
    bulan: "November",
    lengthM: 2588,
    statusSurveyMaterial: "Belum Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 75,
    dateUpdate: ""
  },
  {
    no: 677,
    namaProject: "Relokasi Simpang Cijayanti Bukit Sentul",
    pmoId: "PMO-GOV-677",
    projectId: "GOV0000723",
    jabo: "Jabo 2",
    projectPlan: "Q1-26",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.NETCO",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-11-13",
    tahun: "2026",
    bulan: "Januari",
    lengthM: 3200,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 80,
    dateUpdate: ""
  },
  {
    no: 678,
    namaProject: "Relokasi Crossing Bojong Gede - Kemang",
    pmoId: "PMO-GOV-678",
    projectId: "",
    jabo: "Jabo 2",
    projectPlan: "Q1-26",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.NETCO",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2026-01-14",
    tahun: "2026",
    bulan: "Januari",
    lengthM: 270,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "Project Done",
    categoryConstruction: "Done CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 693,
    namaProject: "[Z1-GOV] Rel.Taman Langsat (bendera)",
    pmoId: "PMO-GOV-693",
    projectId: "",
    jabo: "Jabo 1",
    projectPlan: "Q2-26",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.INTAN",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-11-11",
    tahun: "2026",
    bulan: "Januari",
    lengthM: 3400,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 80,
    dateUpdate: ""
  },
  {
    no: 766,
    namaProject: "Reelokasi Jl.RE.Marthadinata-Jl.Tentara Pelajar",
    pmoId: "PMO-GOV-766",
    projectId: "",
    jabo: "Jabo 2",
    projectPlan: "",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.MANDAU",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2026-03-03",
    tahun: "2026",
    bulan: "April",
    lengthM: 2555,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 80,
    dateUpdate: ""
  },
  {
    no: 767,
    namaProject: "Relokasi Jl.RE.Abdullah - Jl. Merdeka",
    pmoId: "PMO-GOV-767",
    projectId: "",
    jabo: "Jabo 2",
    projectPlan: "",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.SBKP",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-02-13",
    tahun: "2026",
    bulan: "",
    lengthM: 2854,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 50,
    dateUpdate: ""
  },
  {
    no: 768,
    namaProject: "Relokasi Jl Raden Aria Winata - Jl. Aria Surialaga",
    pmoId: "PMO-GOV-768",
    projectId: "",
    jabo: "Jabo 2",
    projectPlan: "Q1",
    areaKota: "South",
    pic: "Chaerulloh",
    waspang: "",
    vendor: "PT.OPTICOM",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-02-18",
    tahun: "2026",
    bulan: "Februari",
    lengthM: 2634,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 80,
    dateUpdate: ""
  },
  {
    no: 772,
    namaProject: "Relokasi JL Jatiuwung ps kemis Segmen 1",
    pmoId: "PMO-GOV-772",
    projectId: "",
    jabo: "Jabo 2",
    projectPlan: "Q1",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.SBKP",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-10-23",
    tahun: "2026",
    bulan: "Mei",
    lengthM: 2400,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 0,
    dateUpdate: ""
  },
  {
    no: 773,
    namaProject: "Relokasi JL Otonom-PS Kemis Segmen 1",
    pmoId: "PMO-GOV-773",
    projectId: "",
    jabo: "Jabo 2",
    projectPlan: "",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.PHPE",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-10-23",
    tahun: "2026",
    bulan: "Mei",
    lengthM: 5012,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 40,
    dateUpdate: ""
  },
  {
    no: 775,
    namaProject: "Relokasi JL Cisauk-Suradita",
    pmoId: "PMO-GOV-775",
    projectId: "GOV0000509,GOV0000592",
    jabo: "Jabo 2",
    projectPlan: "",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.OPTICOM",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "23-Oct-25",
    tahun: "2026",
    bulan: "Mei",
    lengthM: 3500,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 10,
    dateUpdate: ""
  },
  {
    no: 783,
    namaProject: "Relokasi JL Serang - Cilegon",
    pmoId: "PMO-GOV-783",
    projectId: "GOV0000730",
    jabo: "Jabo 2",
    projectPlan: "Q2",
    areaKota: "Tangerang",
    pic: "ARIS BARON",
    waspang: "",
    vendor: "PT.GLOBAL LINK",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2026-01-13",
    tahun: "2026",
    bulan: "Maret",
    lengthM: 1100,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Ready To CO",
    progressConstruction: 100,
    dateUpdate: ""
  },
  {
    no: 792,
    namaProject: "Relokasi Jl Proklamasi -Jl Penataran JakPus FO",
    pmoId: "PMO-GOV-792",
    projectId: "",
    jabo: "Jabo 1",
    projectPlan: "Q4",
    areaKota: "Central",
    pic: "Mega",
    waspang: "",
    vendor: "PT.MANDAU",
    metodeProject: "Relokasi By Apjatel",
    tanggalSurat: "2025-11-20",
    tahun: "2026",
    bulan: "Juni",
    lengthM: 1300,
    statusSurveyMaterial: "Sudah Survey",
    statusSurveyLabour: "Sudah Survey",
    statusConstruction: "In Progress",
    categoryConstruction: "Civil Work",
    progressConstruction: 60,
    dateUpdate: ""
  }
];

// Combine all raw projects correctly, ensuring key properties are parsed nicely
export const PROJECTS_DATA: ProjectData[] = REAL_PROJECTS_DATA.map(p => {
  return {
    no: p.no || (p as any).No || 999,
    namaProject: p.namaProject || (p as any).NamaProject || "",
    pmoId: p.pmoId || (p as any).PMO_ID || "",
    projectId: p.projectId || (p as any).ProjectID || "",
    jabo: p.jabo || (p as any).Jabo || "",
    projectPlan: p.projectPlan || (p as any).ProjectPlan || "",
    areaKota: p.areaKota || (p as any).AreaKota || "",
    pic: p.pic || (p as any).PIC || "",
    waspang: p.waspang || (p as any).Waspang || "",
    vendor: p.vendor || (p as any).Vendor || "",
    metodeProject: p.metodeProject || (p as any).MetodeProject || "",
    tanggalSurat: p.tanggalSurat || (p as any).TanggalSurat || "",
    tahun: String(p.tahun || (p as any).Tahun || ""),
    bulan: p.bulan || (p as any).Bulan || "",
    lengthM: Number(p.lengthM || (p as any).LengthM || 0),
    apdRelokasi: p.apdRelokasi || "",
    statusAudit: p.statusAudit || "",
    apdLinknet: p.apdLinknet || "",
    baSurvey: p.baSurvey || "",
    statusSurveyMaterial: p.statusSurveyMaterial || (p as any).StatusSurveyMaterial || "",
    statusSurveyLabour: p.statusSurveyLabour || (p as any).StatusSurveyLabour || "",
    requestType: p.requestType || "",
    labour: p.labour || "",
    volume: p.volume || "",
    poNumber: p.poNumber || "",
    typePoLabour: p.typePoLabour || "",
    statusPengajuanPo: p.statusPengajuanPo || "",
    remarks: p.remarks || "",
    statusConstruction: p.statusConstruction || (p as any).StatusConstruction || "Not Started",
    categoryConstruction: p.categoryConstruction || (p as any).CategoryConstruction || "",
    progressConstruction: Number(p.progressConstruction !== undefined ? p.progressConstruction : ((p as any).ProgressConstruction || 0)),
    dateUpdate: p.dateUpdate || (p as any).DateUpdate || ""
  };
});
